hwjma_basic_config.settings_form:
  path: '/admin/config/highware/basic-settings'
  defaults:
    _form: '\Drupal\hwjma_basic_config\Form\SettingsForm'
    _title: 'SettingsForm'
  requirements:
    _permission: 'access administration pages'
  options:
    _admin_route: TRUE
